name: Work Profile CI/CD Pipeline (GHCR)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write


    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin  

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/workprofile:latest .

      - name: Run container from image
        run: |
          docker run -d -p 8080:5000 --name workprofile_container ghcr.io/${{ github.repository_owner }}/workprofile:latest
          sleep 5

      - name: Test "/" endpoint
        run: |
          curl --fail http://localhost:8080/ || exit 1

      - name: Test "/health" endpoint
        run: |
          curl --fail http://localhost:8080/health || exit 1

      - name: Stop and remove container
        run: |
          docker stop workprofile_container
          docker rm workprofile_container

      - name: Tag image with commit SHA
        run: |
          docker tag ghcr.io/${{ github.repository_owner }}/workprofile:latest ghcr.io/${{ github.repository_owner }}/workprofile:${{ github.sha }}

      - name: Push both tags to GHCR
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/workprofile:latest
          docker push ghcr.io/${{ github.repository_owner }}/workprofile:${{ github.sha }}